baseURL = "https://spiritsplay.com"
disableLanguages = ["FR"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "misterclarity"
title = "Immerse yourself in Wild Austria!"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 [Coachpedia.](https://coachpedia.net) All Rights Reserved"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "copyright et copie; 2020 [gethugothemes] (https://gethugothemes.com) tous droits réservés"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.main]]
URL = "contact"
name = "contact"
weight = 1
[[menu.main]]
URL = "blog"
name = "blog"
weight = 2
[params]
author = "Coachpedia"
biglogo = ""
description = ""
google_analytics_id = "UA-173554268-1"
logo = ""
post_share = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAyCIAQihbtu9cShJs0kf2IxdIdNckhTEk"
map_latitude = "48.126404"
map_longitude = "16.283692"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "https://static.oracle.com/cdn/apex/19.2.0.00.18/libraries/font-apex/2.1/css/font-apex.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/misterclarity"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/misterclarity"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/mister_clarity"
